name: 쿠폰 크롤러

on:
  schedule:
    # 한국시간 10:07, 10:37, 11:07, 11:37, 17:07
    - cron: '7 1 * * *'
    - cron: '37 1 * * *'
    - cron: '7 2 * * *'
    - cron: '37 2 * * *'
    - cron: '7 8 * * *'
  workflow_dispatch:  # 수동 실행 버튼도 생김

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python 세팅
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: 패키지 설치
        run: pip install -r requirements.txt

      - name: Firebase 키 파일 생성
        run: echo '${{ secrets.FIREBASE_KEY }}' > serviceAccountKey.json

      - name: 크롤러 실행
        run: python main.py